# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paperstart Games
email: paperstartgames@gmail.com
description: "Paperstart Games Website created by Rodrigo Long Chen Kashiwakura"
url: "https://www.paperstartgames.com"
facebook_url:  https://www.facebook.com/paperstartgames/
twitter_url: https://twitter.com/PaperstartGames
youtube_url: https://www.youtube.com/channel/UCBatzH4UKdYjQj9fBLEdf8A

# Build settings
markdown: kramdown
permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-assets

assets:
  prefix: "/assets"
  sources:
    - _assets/css
    - _assets/img
    - _assets/js
  compress:
    css:  sass
    js:   uglifier
